-- Migration 004: Slots
-- Materialised 30-minute windows generated from availability ranges.
-- This is what users see and book. One row = one bookable interview window.

CREATE TABLE slots (
  id               UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- Parent availability range that produced this slot
  availability_id  UUID        NOT NULL REFERENCES availability(id) ON DELETE CASCADE,

  -- Denormalised for fast querying without joins on hot paths
  interviewer_id   UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- Exact UTC boundaries of this 30-min window
  slot_start       TIMESTAMPTZ NOT NULL,
  slot_end         TIMESTAMPTZ NOT NULL,

  status           slot_status NOT NULL DEFAULT 'available',

  -- Audit
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- ─── Constraints ───────────────────────────────────────────────────────────
  CONSTRAINT slot_is_30min CHECK (
    slot_end - slot_start = INTERVAL '30 minutes'
  ),

  -- No two slots for the same interviewer can overlap
  CONSTRAINT no_double_booking_interviewer
    UNIQUE (interviewer_id, slot_start)
);

-- ─── Indexes ─────────────────────────────────────────────────────────────────

-- Primary query: "give me all available slots for this interviewer"
CREATE INDEX idx_slots_interviewer_status
  ON slots(interviewer_id, status);

-- For date-range slot browsing (user scheduling view)
CREATE INDEX idx_slots_start
  ON slots(slot_start)
  WHERE status = 'available';

-- Admin: all slots for a given availability range
CREATE INDEX idx_slots_availability
  ON slots(availability_id);

-- ─── Comments ────────────────────────────────────────────────────────────────
COMMENT ON TABLE slots IS
  'Materialised 30-min windows. Generated by the backend when interviewer sets availability.';
COMMENT ON COLUMN slots.interviewer_id IS
  'Denormalised from availability for join-free queries on the booking path.';
COMMENT ON COLUMN slots.slot_start IS
  'Stored as TIMESTAMPTZ (UTC). Frontend converts to user local time.';
